[project]
name = "pyvasplot"
dynamic = ["version"]

description = "Python toolkit for VASP electronic-structure analysis and visualization."

readme = "README.md"

requires-python = ">=3.12"

authors = [
    { name = "Marek Kopciuszynski", email = "Marek.Kopciuszynski@umcs.pl" },
]

license = "MIT"
license-files = ["LICENSE"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
    "numpy>=1.21",
    "pymatgen>=2026.5.4",
    "matplotlib>=3.4",
    "dill>=0.3.4",
    "tqdm>=4.60",
    "ase>=3.26",
]


[project.optional-dependencies]

dev = [
    "build",
    "pytest",
    "ruff",
]

[build-system]
requires = [
    "setuptools>=77",
    "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"


[tool.pytest.ini_options]
testpaths = ["tests"]